import React from 'react'

export default () => (
  <main>
    <article className='row'>
      <div className='medium-10 medium-push-1 large-8 large-push-2 columns'>
        <header className='fadeInLeft wow'>
          <h1>Terms</h1>
        </header>
        <div className='content fadeInUp wow'>
          <p><strong>Ethical rules</strong></p>
          <p><em>The ethical rules gives a reflection to our own valuations – to protect the children, their development and give them a great knowledge about digital money.</em></p>
          <p>At Gimi we are working in a way that gives children the opportunity to learn in a comfortable and pedagogical tempo how to handle their own money and prepare themselves for the life as a grown-up. Below you can take part of our ethical rules that shows how we relate to children and members of their family that are users at Gimi.</p>
          <p>We want to make clear that our work goes beyond the boundries of Gimi. We dosen’t only want our children to feel safe using our app, but also when they are purchasing items from the Internet or ”internetsurf” in general. We have a continous work where we try to influence other companies to follow the ethic rules that we at Gimi has developed.</p>
          <p>Our ethical rules has been developed with help from educators, psychologists, economists, children and parents. The rules relates to global rules and international laws, and they are customized to the digital world where many youths has access. The rules has been created to show how we at Gimi handles information and behavior among our young users. We think and hope that other operators, who are reaching out to children and youths, will follow our ethical rules so that the childrens development and interests will always come first.</p>
          <p>Areas that we have put focus to when we have worked with our ethical rules are;</p>
          <p>Marketing towards children, Collection of information regarding the children, production and developing services and goods for children, decision environment for children and youths, justification of wrong decisions, support and communication for the whole family.</p>
          <p>Why we have developed our ethical rules?</p>
          <p>Children are today using the Internet more and more and by only 3 years most children are online. Early, children are exposed to messages and information from companies. They have to make decisions when it comes to purchases and make other different choices. That children is exposed to advertisements and commercials pointed towards them is a reality that we have to accept. We find it extremely important, with this kind of exposed market, that behavior, marketing and ethical rules is adjusted the children. It is the children that should be able to use the Internet, not the other way around.</p>
          <p><strong>Our ethical rules</strong></p>
          <p><strong>Purchases should be adjusted to the children</strong></p>
          <p>We think that the purchase offers should be adapted to the children. Today, the children are more exposed to information and offers through the internet.  It’s difficult to see a clear line between what is incitements and what is just sharing information. It’s important that apps and companies gets aware of how they reach out to children. If their approach and purpose is to trick the children into purchasing items, the children are not going to be able to get the right knowledge about handling their own money.</p>
          <p><strong>Education and lessons learned will be at focus</strong></p>
          <p>Our vision is that society should help educating children about economy in a fun and pedagogical way. The purpose with lessons learned is to make sure that the children will be able to think for themselves, hit their own solutions in a safe environment and create more innovation.</p>
          <p><strong>Decisions are supposed to prepare the children for the grown-up life</strong></p>
          <p>It’s important that the children learns how to take responsibility . By putting children in a safe and comfortable zone, you will not challenge them and maybe even stop their ability to get a fast curve of learning. Children is supposed to be able to take different kind of choices, right and wrong, so that they after a while can eliminate the wrong choices when it comes to economy and purchases. We will create a method for children so that they can implement their choices and let the parents adjust the responsibility after how mature behavior the children shows.</p>
          <p><strong>The children will owe their own money</strong></p>
          <p>In a pedagogical way, we would like to give the children a greater understanding for money by giving them responsibility for their own money. It’s important that children can decide what they would do with the money. Making wrong decisions when it comes to economical actions will make the children take better decisions next time when it is a similar purchase.</p>
          <p><strong>The child should be able to make a dections in his own tempo</strong></p>
          <p>Children should be able to decide over their own economy without any influence from commercials, misleading messages or the ”must-have” society.</p>
          <p><strong>Stop – think – buy is a good method</strong></p>
          <p>It is only positive that the children gets space to reflect over their decisions before they buys something. There should be time for reflections and collecting information connected to the purchase, adjusted to the size of the purchase. A fine example for enough time for reflection is where the seller pauses the purchasing process and encourage you to press an additional button to finalize your purchase.</p>
          <p><strong>Clarity &amp; Overview</strong></p>
          <p>It should be easy to see when a purchase has been completed and what any extra costs you can expect. Many children buys stuff from the internet these days, without the knowledge that there is a cost connected with the decision. Generating clarity to create an understanding for decision making and even the consequence from purchases is our ”perfect picture” how a purchasing process for children should be.</p>
          <p><strong>Accentuate economical conversations within the family</strong></p>
          <p>The economical conversations between children and parents at home is important. A good time to discuss around the economical topic is when the family is gathered. By doing that you give the children the opportunity to take part of the day to day economy at home. Parents should talk about money, not only where there is no more money left, but also as something exciting. In the end that will lead to a positive setting.</p>
          <p><strong>How we handle information and data</strong></p>
          <p>Childrens information is sensitive. That is why we have adjust our handling of information in a way that protects the information and at the same time creates a safe environment to handle money.</p>
          <p><strong>Handling data</strong></p>
          <p>We gather information from our users so that we can learn more about children and parents behavior. That information gives us the opportunity to develop and make our service better for the users. We collect all of our information safely, and we will never use the information for marketing offers or other incentives directed towards children.</p>
          <p><strong>Handling pictures</strong></p>
          <p>Uploaded pictures from users will not be used by Gimi for external use.  The pictures has only one purpose. To improve the users experience.</p>
          <p><strong>Personal information</strong></p>
          <p>The childs phone number, name and other personal information will be placed in our database. We will never take any part in this information, except from some circumstances when we will try to help users that needs to resetting or upgrade their account.</p>
          <p><strong>A safe platform for communication</strong></p>
          <p>We do not take any part when it comes to communication between users. Communication is suppose to improve the user experience and improve the communication at home when it comes to money.</p>
          <p><strong>Marketing aimed at children</strong></p>
          <p>Gimi will never do marketing aimed at children without any permission from the parents. The marketing will never take advantage from the childrens good beliefs and not contain any direct purchase solicitations.</p>
          <p><strong>We are not using in-app purchases for children</strong></p>
          <p>At Gimi the children are not able to implement in app-purchases, and can therefore not be encouraged to upgrade their service in change for money.</p>
          <p><strong>Our ethical rules follows</strong></p>
          <p>The UN Convention on the Rights of the Child</p>
          <p>We follow ”the UN convention on the rights of children” where the childrens rights shall come at first in every situations that includes children.</p>
          <p><a href='http://www.manskligarattigheter.se/sv/de-manskliga-rattigheterna/vilka-rattigheter-finns-det/barnets-rattigheter'>http://www.manskligarattigheter.se/sv/de-manskliga-rattigheterna/vilka-rattigheter-finnsdet/barnets-rattigheter</a></p>
          <p>The ethical rules are suppose to follow (marknadsföringslagen) and make sure that marketing is not misguiding or agressive, and that it will be forbidden if it effetcs the consuments ability to make a reasonable decision.</p>
          <p>Our ethical rules agrees with the swedish governments study september 2012 that shows the misguiding and negative effects by encouraging children to purchases in apps, ”in-app purchases” <a style={{color: 'blue'}} href='http://www.etiskaradet.se/'>http://www.etiskaradet.se/</a><u>.  </u>We agrees even with the Ethical council for payment services that has been developed for marketing and the content in payment services. Marketing are not allowed to happen if it reaches out to children under 14 years old, and the cost for the service exceeds 10 kroners.</p>
          <p><strong>ICC;s Rules for commercial and marketing communication</strong></p>
          <p>Our ethical rules follows article 18 in the ICC-rules and the particular demands that is set when it comes to marketing and commercials towards children and youths. If you look at article 18 you can see that certain demands has to be followed when it comes to marketing that reaches out to children and youths. It is not allowed to affect positive social behaviors, life styles or attitudes. Products who are inappropriate for children and youths are not allowed marketing in media, and these products are also supposed to be marked ”inappropriate for children”. Marketing are not allowed to take advantage of childrens young and natural goodwill and lack of experience. It is neither supposed to contain pictures or words that can give physical damages, or can effect someone in a negative way mentally or morally. Children and youths are not allowed to be pictured in situations that contains high risk, or activities where they can get injured or encourage others to take part of those kinds of activities. Children and youths can be effected negative from marketing that contains violence. In general commercial is not allowed to encourage to violence or give the impression that the attitude towards violence is ok. The ICC-rules also contains rules about social ratings. Marketing is not suppose to give the impression that a certain product gives a child or youth physical , socially or psychological advantages over children at same age.</p>
          <p>&nbsp;</p>
          <p className='p1'><span className='s1'><b>Gimi Terms of Service</b></span></p>
          <p className='p1'><span className='s1'><b>Personal Integrity</b></span></p>
          <p className='p1'><span className='s1'>Being a collaborative community our top-priority will always be the relationship with our community. We are therefore firmly committed to the security and protection of integrity of our Users of the Services and their contacts.</span></p>
          <p className='p1'><span className='s1'>The Gimi Privacy Policy further describes what information You may share with Gimi and other Users and how Gimi may use and share such information.</span></p>
          <p className='p1'><span className='s1'><b>Consent to Use of Data</b></span></p>
          <p className='p1'><span className='s1'>You agree that Gimi, in accordance with the Gimi Privacy Policy, may collect and use technical data such as Your IP address, device ID, usage data and related information, including but not limited to technical information about Your mobile device, system and application software, and peripherals, that is gathered periodically to facilitate the provision of software updates, product support and other services to You related to the Gimi Apps.</span></p>
          <p className='p1'><span className='s1'><b>Obligations and Restrictions to Use of Services</b></span></p>
          <p className='p1'><span className='s1'>You guarantee that any Contact Information and other data, such as Your profile information, You may transfer to Gimi as a User of the Services (together “Content”), to the best of Your knowledge, is not false or otherwise may corrupt or disrupt the Services and that you have the right to share it with Gimi and other Users.</span></p>
          <p className='p1'><span className='s1'>You shall not by any commercial means use the Services or otherwise transfer for value the Services or the Content. You agree not to challenge Gimis’s rights in or otherwise attempt to assert any rights in the Services, except those explicitly granted under these Terms. You agree not to use the Services except as expressly permitted under these Terms.</span></p>
          <p className='p1'><span className='s1'>Scraping of any information contained in the Services, including any third party information accessible via the Services, is strictly prohibited.</span></p>
          <p className='p1'><span className='s1'>The Services or the Content may not be used in any way, which is illegal, harmful or may be considered offensive by Gimi, other Users or third parties. You therefore agree not to exploit the Services in any unauthorized way whatsoever, including but not limited to, trespass or burdening network capacity. You further agree not to use our Services in any manner to harass, abuse, stalk, threaten, defame or otherwise infringe or violate the rights of any other party, and You acknowledge and agree that Gimi is not in any way responsible for any such use by You, nor for any harassing, threatening, defamatory, offensive or illegal messages or transmissions that You may receive as a result of using the Services. Notwithstanding any other remedies available to Gimi, You agree that Gimi may suspend or terminate Your use of the Services without notice.</span></p>
          <p className='p1'><span className='s1'>You may contact Gimi at info@veckopengen.se to report any violation or infringement of Your rights by Users of the Services.</span></p>
          <p className='p1'><span className='s1'><b>Proprietary Rights</b></span></p>
          <p className='p1'><span className='s1'>The Services are protected by copyright laws and international copyright treaties, as well as other intellectual property laws and treaties. Gimi and its licensors shall retain ownership in and to the Services and to all related intellectual property rights, including without limitation trademarks, trade names, database rights and patents. You are granted only a limited right to use the Services subject to these Terms.</span></p>
          <p className='p1'><span className='s1'><b>Scope of License</b></span></p>
          <p className='p1'><span className='s1'>Your compliance with these Terms at all times, Gimi grants You a personal, limited and non-exclusive right to use the Services for Your own personal, non-commercial use. This license does not allow You to use the Gimi Apps on any mobile device that You do not own or control. You may only redistribute the Gimi Apps unmodified for non-commercial purposes to a party that has agreed to these Terms. You may not copy (except as expressly permitted by these Terms), decompile, reverse engineer, disassemble, attempt to derive the source code of, modify, or create derivative works of the Gimi Apps, any updates, or any part thereof (except as and only to the extent any foregoing restriction is prohibited by applicable law or to the extent as may be permitted by the licensing terms governing use of any open sourced components included in the Gimi Apps).</span></p>
          <p className='p1'><span className='s1'>The license does not allow You to use Gimi’s name, trademarks or other commercial symbols. All rights and licenses not expressly granted to You under these Terms shall be retained by Gimi.</span></p>
          <p className='p1'><span className='s1'><b>Support</b></span></p>
          <p className='p1'><span className='s1'>Gimi strives to provide adequate and efficient technical support, upgrades and updates for the Services. Gimi shall not, however, be under any obligation to provide support or maintenance for the Services under these Terms and reserves the right to limit the support, upgrades and updates provided from time to time.</span></p>
          <p className='p1'><span className='s1'><b>Termination</b></span></p>
          <p className='p1'><span className='s1'>Your right to use the Services continues until these Terms are terminated. Gimi may terminate them and Your use of the Services at any time. You may terminate them at any time by uninstalling the Gimi Apps and ceasing the use of the Services. These Terms will automatically terminate if You fail substantially to comply with them. Upon any termination, You agree to stop using the Services. Upon termination by You, or by Gimi due to Your breach of these Terms, You will not be refunded any part of the Services, license fees or other prepaid fees, if any. Upon termination by Gimi without cause, You will be refunded such prepaid fees following a written request by Yourself, provided a receipt for such fees and a clear payment instruction are included.</span></p>
          <p className='p1'><span className='s1'>Any prepaid fees for the Services are connected to the User device as well as its phone number. Therefore, if You change device or its SIM-card, You cannot transfer the balance to a new device or SIM-card and no refund will be available in such cases. Gimi reserves the right, at its own discretion, to remove any remaining balance resulting from prepaid fees without any right of refund twelve (12) months from the purchase.</span></p>
          <p className='p1'><span className='s1'>Provisions of sections No Warranty, Limitation of Liability, and Termination shall survive any termination of these Terms.</span></p>
          <p className='p1'><span className='s1'><b>Assignability</b></span></p>
          <p className='p1'><span className='s1'>Gimi reserves the right, at its own discretion, to freely assign and transfer the rights and duties under these Terms to any third party.</span></p>
          <p className='p1'><span className='s1'><b>Additional and Changed Terms</b></span></p>
          <p className='p1'><span className='s1'>As Gimi provides global Services, additional Terms of Services may apply to Users in certain jurisdictions and will in such cases be made available in appendices hereto.</span></p>
          <p className='p1'><span className='s1'>In case of material changes, the User shall always be notified thereof via publication on the Gimi website and provided the option to immediately terminate the Services. The revised Terms shall become effective upon such publishing or notification to the User. You will always find the latest version of these Terms at www.gimitheapp.com.</span></p>
          <p className='p1'><span className='s1'><b>No Warranty</b></span></p>
          <p className='p1'><span className='s1'>To the maximum extent permitted by applicable law Gimi makes no warranty or representation, either expressed or implied with respect to the services, their quality, performance, merchantability, fitness for a particular purpose or non-infringement of third party rights. As a result, the services are provided ”as is” and you are assuming the entire risk as to their quality and performance.</span></p>
          <p className='p1'><span className='s1'>You understand and acknowledge that Gimi will not be liable for network-related problems attributable to the operation of the Services and that network configuration changes may affect the Services’ performance.</span></p>
          <p className='p1'><span className='s1'>Gimi makes no representation that the Services are available for use in any particular location. To the extent You choose to access the Services, You do so at Your own initiative and are responsible for compliance with any applicable laws, including but not limited to applicable local laws.</span></p>
          <p className='p1'><span className='s1'><b>Force Major</b></span></p>
          <p className='p1'><span className='s1'>Parties are not responsible for delays or loss due to circumstances that the party has no control over and which significantly impedes the fulfilment of the obligation in question or that causes the fulfilment of the obligation is not economically justifiable.</span></p>
          <p className='p1'><span className='s1'><b>Limitation of Liability</b></span></p>
          <p className='p1'><span className='s1'>To the extent not prohibited by law, you expressly agree that Gimi shall in no event be liable for any direct, indirect, special, incidental, consequential or exemplary damages, including but not limited to damages for loss of profits, data and goodwill, arising out of the use or inability to use the services or the content, even if advised of the possibility of such damages. In particular, and without limitation, Gimi shall have no liability for any information stored or processed within the Services, including the costs of recovering such information. Your only right or remedy with respect to any problems or dissatisfaction with the Services, is to uninstall the Gimi Apps and cease use of the Services.</span></p>
          <p className='p1'><span className='s1'>Gimi shall not be liable for the validity and correctness of the content provided through and in connection with use of the services. Any use of the information obtained through the use of the services shall be done at your own discretion and risk.</span></p>
          <p className='p1'><span className='s1'>Gimi controls and monitors Content made available by the Users via the Services, but can nevertheless not guarantee its origin and correctness. Therefore, You accept that You via the Services may be exposed to information that is erroneous or otherwise objectionable. Gimi shall not be liable for the Content and other information disseminated or delivered through or in connection with the Services. You agree that You shall bear all risks associated with the use of such information.</span></p>
          <p className='p1'><span className='s1'>Nothing in this section Limitation of Liability shall, however, limit or exclude the Responsible Publisher’s liability under the Swedish Fundamental Law on Freedom of Expression.</span></p>
          <p className='p1'><span className='s1'><b>Governing Law</b></span></p>
          <p className='p1'><span className='s1'>Your use of the Services and their various functionalities and the ensuing relationship between you and Gimi are governed by these Terms, which shall be construed in accordance with, and governed by, the laws of Sweden, excluding its choice of law rules. All disputes relating to these Terms shall exclusively be adjudicated in Sweden, with the District Court of Stockholm as the court of first instance.</span></p>
          <p className='p1'><span className='s1'><b>Gimi Privacy Policy</b></span></p>
          <p className='p1'><span className='s1'>Gimi is an application that is intended to be used by children and parents to manage money.</span></p>
          <p className='p1'><span className='s1'>Our website (www.gimitheapp.com) is for parents, while our app are designed for the whole family, including young children with parent supervision. We take privacy seriously at Gimi and this policy is designed to share what information we collect and how we use it. We last updated the contents of this policy on 21/3-2016. Gimi may change or update the Privacy Policy at any time. Unless another date is given, the changes are effective upon posting. Thus, you should review the Privacy Policy frequently. This Privacy Policy is also part of the Terms of Service that explain your rights and responsibilities when using Gimi’s services and sites.</span></p>
          <p className='p1'><span className='s1'>Gimi (“we”) offer users (“You”) a service which purpose is to help the family to handle the children’s economy and educate children about digital money.</span></p>
          <p className='p1'><span className='s1'>Being a collaborative community the top-priority of Gimi will always be the relationship with its community. Gimi is therefore firmly committed to the security and protection of the personal integrity of our Users of the Services (as defined in the Terms of Service) and their contacts.</span></p>
          <p className='p1'><span className='s1'>Downloading and Installing a Gimi Application means that you agree to the Terms of Service and Privacy Policy.</span></p>
          <p className='p1'><span className='s1'>If you don’t agree with this Privacy Policy or the Terms of Service, you should not use the sites and services. If you have any questions please contact us at info@veckopengen.se</span></p>
          <p className='p1'><span className='s1'><b>Contractual Relationsship</b></span></p>
          <p className='p1'><span className='s1'>These Conditions of use (“Conditions”) govern the access or use by you, an individual, and applications, websites, content, products and services (“Services”) made available by Gimi.</span></p>
          <p className='p1'><span className='s1'>Please read these Conditions very carefully before accessing or using the Services.</span></p>
          <p className='p1'><span className='s1'>Your access or use of the Services constitutes your agreement to be bound by these Conditions, which establishes a contractual relationship between you and Gimi.</span></p>
          <p className='p1'><span className='s1'>The access or use of the Services by any child under your parental responsibility constitutes your agreement to be bound by these Conditions, which establishes a contractual relationship between you and Gimi.</span></p>
          <p className='p1'><span className='s1'>IF YOU DO NOT AGREE TO THESE TERMS, YOU OR ANY CHILD UNDER YOUR PARENTAL RESPONSIBILITY MAY NOT ACCESS OR USE THE SERVICES.</span></p>
          <p className='p1'><span className='s1'><b>Information Collected and Received</b></span></p>
          <p className='p1'><span className='s1'><i>Installation and Use</i></span></p>
          <p className='p1'><span className='s1'>When you install and use the Gimi Apps, Gimi will collect, process and retain personal information from You and any devices you may use in Your interaction with our Services. This information may include the following: geo-location, Your IP address, data usage, device ID or unique identifier, device type, ID for advertising, ad data, unique device token, operating system, operator, connection information, screen resolution, usage statistics, version of the Gimi Apps You use and other information based on Your interaction with our Services.</span></p>
          <p className='p1'><span className='s1'><i>User Profile</i></span></p>
          <p className='p1'><span className='s1'>Where the User registers a user profile in the Gimi Apps with via SMS and/or e-mail verification, the User confirms being the holder of a certain number and e-mail-address. The information up-loaded to the profile section of the Gimi Apps will be received and stored by Gimi until the User changes or deletes such data or terminates the Services. Compulsory information when creating a profile is the User’s phone number, email, choice of children or parent and additional information that may be provided at the User’s option include, but is not limited to, photo, gender, street address and zip code, country of residence, professional website, Facebook page, Twitter adress, Instagram account and a short status message. Gimi may supplement the information provided collected with information from third parties and add it to information provided by You.</span></p>
          <p className='p1'><span className='s1'>Please note that any content uploaded to and displayed in the user profile by the User is not moderated by Gimi and is not protected under the Swedish Fundamental Law on Freedom of Expression. The User is solely liable for the publication of such content.</span></p>
          <p className='p1'><span className='s1'><i>Identifiers</i></span></p>
          <p className='p1'><span className='s1'>In addition, You may provide us with Your user identifier information regarding certain third party services, i.e Facebook, Google+, LinkedIn and Twitter, necessary for the application to interoperate with such third party services. In that case Gimi will store and process also that information (and also mapped photo where applicable), for as long as You use the Services and will not use this information for any other purpose than required in order to obtain interoperability and functionality in relation to such third party services. Please note that we never store any passwords to the mentioned third party services.</span></p>
          <p className='p1'><span className='s1'><i>Contact Information</i></span></p>
          <p className='p1'><span className='s1'>If you provide us with personal information about someone else, you confirm that they are aware that You have provided their data and that they consent to our processing of their data according to our Privacy Policy.</span></p>
          <p className='p1'><span className='s1'><i>Please note that no other Contact Information, than the phone numbers and thereto attached names and email addresses will be received, stored and used from the User’s address Book. Other numbers or information that may be contained in your device’s phone book will be filtered away and therefore not be stored or used by Gimi. Addresses, passwords and credit card numbers and any other similar information will automatically be prevented from being entered into the Gimi database by our safety algorithms, that filters any number and other information stored in the phone book in a number sequence not compatible with that used for telephone numbers. Please also note that You always choose not to share Contact Information with Gimi and if You have shared information and changed Your mind, You can easily delist Your number or opt-out to render your entire Contact Information unavailable for search in the database.</i></span></p>
          <p className='p1'><span className='s1'>Opt-in/registration</span></p>
          <p className='p1'><span className='s1'>With the Gimi apps Your are provided with a fast and smart signup process for Your phone that, among other features, will provide instant search results from Your phonebook. Apart from Your location when performing an active search, and exclusively for the purpose of optimizing the search result, no further data or information that accounted for in the Terms and this Privacy Policy will be processed when You use the Gimi Apps opt-in (and such location data will not be stored).</span></p>
          <p className='p1'><span className='s1'><b>Use, Sharing and Disclosure of User and Contact Information</b></span></p>
          <p className='p1'><span className='s1'>Information related to the User or Contact Information will be used to:</span></p>
          <ol className='ol1'>
            <li className='li1'><span className='s1'><span className='s1'>Enable Gimi Name Search, as described below, to Users who have activated that functionality,</span></span></li>
            <li className='li1'><span className='s1'><span className='s1'>Contact you from Gimi for verification purpose or with information pertaining to the Services, e.g. newsletter e-mails and similar notifications, and verify provided User Profile information with third party providers,</span></span></li>
            <li className='li1'><span className='s1'><span className='s1'>Deliver messages through the Gimi apps,</span></span></li>
            <li className='li1'><span className='s1'><span className='s1'>Enable You to use and share Your user information in connection with Your use of third party services,</span></span></li>
            <li className='li1'><span className='s1'><span className='s1'>Customize, measure and improve our Services, and</span></span></li>
            <li className='li1'><span className='s1'>Personalize, measure and improve our advertising and use geo-location information to provide You with location based information and services (such as advertising, search results and other personalized content).</span></li>
          </ol>
          <p className='p1'><span className='s1'><i>Miscellaneous</i></span></p>
          <p className='p1'><span className='s1'>In addition to the above Gimi may disclose information related to the Users and Contact Information if we believe such action is necessary to:</span></p>
          <ol className='ol2'>
            <li className='li1'><span className='s1'>comply with the law, or legal process served on us;</span></li>
            <li className='li1'><span className='s1'>protect and defend our rights or property (including the enforcement of our agreements); or</span></li>
            <li className='li1'><span className='s1'>act in urgent circumstances to protect the personal safety of Users or members of the public.</span></li>
          </ol>
          <p className='p1'><span className='s1'>Gimi may share Your personal data with trusted third party service providers and partners. Gimi will always require these parties to take appropriate organizational and technical measures to protect your personal data and traffic data and to observe the relevant legislation.</span></p>
          <p className='p1'><span className='s1'>The following is a description of how Gimi may share information about You with trusted third party partners:</span></p>
          <ol className='ol1'>
            <li className='li1'><span className='s1'>Gimi uses a third party partner company in order to send You or a third party you wish to contact SMS when you use the Services. In order to send you the SMS; we send the third party company Your and the relevant third party’s phone numbers for the transmission of requested SMS.</span></li>
            <li className='li1'><span className='s1'>Gimi may use Push Notification Services to notify you about up-dates and important information. In such cases, Your phone number may be part of the notification. This message is sent to the push notification service provider, for delivery to Your device. You may, however, at any time-opt out or disable push notifications.</span></li>
            <li className='li1'><span className='s1'>Gimi may allow you to use third party services to create your user profile or log in to use our Services, share information with such third parties, or to connect your user profile with the respective third parties. Those third parties may automatically provide us with access to certain personal information retained by them about You (e.g., content viewed by you, content liked by You and information about the advertisements you have been shown or may have clicked on). You control the personal information You allow us to have access to through the privacy settings on the respective third party service and the permissions You give us when You grant us access to the personal information about You retained by the respective third party service. By associating an account managed by a third party with Your Gimi user profile and authorizing us to have access to this information, You agree that we may collect, use and retain the information provided by these third party services in accordance with this Privacy Policy. As an example, Gimi may send a queried telephone number to Twitter in order to verify it against the Twitter API or retrieve the holders’ Twitter ID or Twitter photo, if available. If the Twitter ID is available, Gimi will display a Tweet and follow button in the Users’ Gimi apps, which the User may use to send an open tweet to, and start to follow, the holder of the number. The Gimi apps is not, however, designed to be a Twitter communication application and You will not be able to retrieve the replied or further tweets to the Gimi apps. When using the Twitter functionalities You are bound by the Twitter Terms of Service, located at <a style={{color: 'blue'}} href='http://twitter.com/tos'>https://twitter.com/tos</a>, and the Twitter privacy policy, located at <a style={{color: 'blue'}} href='https://twitter.com/privacy'>https://twitter.com/privacy</a>.</span></li>
            <li className='li1'><span className='s1'>For the provision of free versions of the Services, Gimi may also collaborate with a few selected third party advertising networks, which in such case may be provided limited information related to the freemium User’s device (but no other User or Contact Information).</span></li>
            <li className='li1'><span className='s1'>Gimi, or a third party on its behalf, may collect and use your email address, telephone number and ID for advertising (including, but not limited to, content viewed by you, content you have commented on and information about the advertisements you have been shown or may have clicked on) through the Gimi apps and share this information with third party advertisers and networks. Such third parties may use this information and information collected from other sources in order to provide measurement services and targeted ads. You can limit or opt-out of the collection and use of Your information for ad targeting by third parties via Your device settings.</span></li>
          </ol>
          <p className='p1'><span className='s1'>The submission of Contact Information by You and the processing thereof by Gimi is constitutionally protected under the applicable law, see the Gimi Terms of Service. Gimi may, however, disclose information contained in the Service and about you if we determine that for national security, law enforcement, or other issues of public importance that disclosure of information is necessary, always provided, of course, it is also lawful.</span></p>
          <p className='p1'><span className='s1'>Gimi may from time to time ask you to provide information on your experiences from using the Gimi Services, which will be used to measure and improve quality. You are at no time under any obligation to provide any of such data. Any and all information which is voluntarily submitted in feedback forms or any surveys that You accept to take part in is used for the purposes of reviewing this feedback and improving the Gimi software, products and websites.</span></p>
          <p className='p1'><span className='s1'><b>Cookies and Automatically collected information</b></span></p>
          <p className='p1'><span className='s1'>The Gimi Website uses so called “Cookies” in connection with the Services. Cookies are pieces of information stored on Your computer’s hard drive and/or other device’s browser that enables Gimi to keep Your login session for thirty days. The use of Cookies is standard practice. Cookies do not enable any access to and/or inspection of other information on Your computer or other device. If You do not wish to receive cookies, or wish to be notified of when they are placed, You may set your web browser to do so, if your browser so permits. Please understand that if Cookies are turned off, You may not be able to obtain full functionality in certain parts of the Services.</span></p>
          <p className='p1'><span className='s1'>The Gimi website and the Gimi Apps use Google Analytics, a web analytics solution by Google. Google Analytics also adds cookies to Your computer or mobile device when You visit our website or interact with certain parts of the Gimi Apps and collects usage information to create statistics for Gimi. See <a style={{color: 'blue'}} href='http://www.google.com/privacy.html'>Google’s privacy policy</a> for details.</span></p>
          <p className='p1'><span className='s1'>We also use the analytics-tool Mixpanel to measure the use of the Gimi apps, to learn more about the terms of Mixpanel read their terms here: <a href='https://mixpanel.com/terms/'>https://mixpanel.com/terms/</a></span></p>
          <p className='p1'><span className='s1'>The Gimi website also embeds badges from the social networking sites <a style={{color: 'blue'}} href='http://www.facebook.com/'>Facebook</a> and <a style={{color: 'blue'}} href='http://twitter.com/'>Twitter</a>. The badges may add cookies to Your computer or mobile device when You use the Services and have enabled Facebook connection. See <a style={{color: 'blue'}} href='http://www.facebook.com/policy.php'>Facebook’s privacy policy</a>, <a style={{color: 'blue'}} href='http://www.google.com/privacy.html'>Google’s privacy policy</a> and <a style={{color: 'blue'}} href='https://twitter.com/privacy'>Twitter’s privacy policy</a> for details.</span></p>
          <p className='p1'><span className='s1'>Gimi servers may automatically collect data about Your Internet address when You use the Gimi Services. This information, known as an Internet Protocol address, or “IP Address”, is a number that is automatically assigned to Your computer or other device by Your Internet service provider whenever You are on the Internet. When You request pages from the Services, our servers may log Your IP Address and, if applicable, Your domain name. Your IP Address is used to help identify You and to gather demographic information about our Users as a whole. Gimi’s servers may also record the referring page that linked you to Gimi (e.g. another web site or a search engine); the pages You visit on the Services; the web site you visit after Gimir’s web site; the ads you see and/or click on; other information about the type of Web browser, computer, platform, related software and settings you are using; any search terms You have entered on this web site or a referral site; and other Web usage activity and data logged by Gimi’s servers. Gimi uses this information for internal system administration, to help diagnose problems with servers, and to administer our Services. Such information may also be used to gather demographic information, such as country of origin and Internet Service Provider.</span></p>
          <p className='p1'><span className='s1'>Gimi automatically gather, analyze and aggregate User data in order to improve Our services. Data gathered is stored and protected in Our servers. By accepting the Privacy Policy and Terms of Service the User agree to all data generated by Users within the Gimi Apps belongs to Gimi.</span></p>
          <p className='p1'><span className='s1'><b>Information Security</b></span></p>
          <p className='p1'><span className='s1'>In order to provide the Gimi Services, Gimi may transfer, process and store personal data in a number of countries. Gimi may also subcontract processing of Your information to third parties located in countries other than Your home country. Information collected within the European Economic Area (“EEA”) may, for example, be transferred to and processed in a country outside of the EEA, which may not provide the same level of protection for personal data as within the EEA. You acknowledge and agree that Gimi may transfer Your personal data as described above for purposes consistent with this Privacy Policy. We take all reasonable precaution to protect Your information, Contact Information and other Content from misuse, loss and unauthorized access. Although we cannot guarantee this information will not be subject to unauthorized access, Gimi has physical, electronic, and procedural safeguards in place to protect it. The Information is stored on secured servers and protected by secured networks to which access is limited to a few authorized employees and personnel. However, no method of transmission over the Internet, or method of electronic storage, is 100% secure.</span></p>
          <p className='p1'><span className='s1'><b>Accuracy of Collected Information</b></span></p>
          <p className='p1'><span className='s1'>Gimi may on its own initiative, or at your request, replenish, rectify or erase any incomplete, inaccurate or outdated information retained by Gimi in connection with the operation of the Services. You have always the right to know what information is stored about You and have any data corrected or deleted on Your request, which should be submitted in accordance with our contact details below.</span></p>
          <p className='p1'><span className='s1'>The accuracy and security of information concerning the Users and their contacts are Gimi’s highest priority and they are free to opt-in or opt-out of the Services at any time.</span></p>
          <p className='p1'><span className='s1'>If you use a service, feature, or functionality that is operated by a third party and made available through our Services (including Services we jointly offer with the third party), each party’s terms will govern the respective party’s relationship with you. Gimi is not responsible or liable for those third party’s terms or actions taken under the third party’s terms.</span></p>
          <p className='p1'><span className='s1'><b>Changes to this Privacy Policy</b></span></p>
          <p className='p1'><span className='s1'>Gimi may at any time with or without a separate notice change this Privacy Policy, and You are encouraged to review this Policy from time to time on the website www.gimitheapp.com. In case of substantial changes, Gimi notifies the Users by push notice or via notice on the Gimi website.</span></p>
          <p className='p1'><span className='s1'><b>Contact</b></span></p>
          <p className='p1'><span className='s1'>If You have any additional questions about Gimi’s Terms of Service or Privacy Policy or want to make a request regarding certain information, You are encouraged to contact Gimi.</span></p>
          <p className='p1'><span className='s1'>The contact information is:</span></p>
          <p className='p1'><span className='s1'>GimiAB, Reg. No. 556985-8029, Skeppsbron 44, 4 tr 111 30 Stockholm, Sweden.</span></p>
          <p className='p1'><span className='s1'>You can also send your enquiries via email to info@gimitheapp.com</span></p>
          <p className='p1'><span className='s1'>For Users that may have grievances pertaining to the Services, Gimi has appointed a Grievance Officer to deal with Your issues. You may reach him/her at support@gimitheapp.com</span></p>
        </div>
      </div>
    </article>
  </main>
)
